[package]
name = "bento"
version = "0.1.0"
edition = "2021"

[dependencies]
cgroups-rs = "0.2"
clap = { version = "3.2", features = ["derive", "unstable-v4"] }
color-eyre = "0.6"
eyre = "0.6"
nix = "0.25"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"

[package.metadata.cross.build]
default-target = "aarch64-unknown-linux-gnu"

[package.metadata.cross.build.env]
passthrough = ["RUST_BACKTRACE", "RUST_LOG"]
